### PR TITLE
zfsbootmenu-ui.sh: fix typo in fallback message

### PR DESCRIPTION
**Pull request by zenodotus280**

### CODE REVIEW

**Comment by ahesford** [comment]
Please fix the typo in the commit message:

    fsbootmenu-ui.sh -> zfsbootmenu-ui.sh

**Comment by zenodotus280** [comment]
The irony.
Fixed.

**Comment by ahesford** [comment]
Not the issue title, but the commit message.

**Comment by zenodotus280** [comment]
Done.

**Comment by zdykstra** [comment]
Thanks!

**Pull request merged**
