### PR TITLE
zfsbootmenu: warn when canmount=on is set for root dataset

### PR DESCRIPTION
**Pull request by zdykstra**
Root datasets should never be automatically mounted. Anything that is considered a root dataset (regardless of a valid kernel/initramfs pair being present) should be checked for `canmount=on` being set. If it is, throw up a zwarn() . This possibly needs to be more aggressively warned via a timed_prompt - forcing user interaction.

### CODE REVIEW

**Review by ahesford — APPROVED** [review]
I think a subtle warning like this or a more obvious, passive indicator is fine. I don't know that we should interrupt regular flow with a timed prompt.

**Review by ahesford — APPROVED** [review]
I think a subtle warning like this or a more obvious, passive indicator is fine. I don't know that we should interrupt regular flow with a timed prompt.

**Comment by zdykstra** [comment]
Yeah. If we continue to see people impacted by this, the warning can be re-evaluated. For now, a normal warning delivered via the common mechanism is a good start.

**Comment by ahesford** [comment]
How about this: count the number of root filesystems; if there is exactly one and has `canmount=auto`, use the unobtrusive logged warning. If there are more than one and any of them have `canmount=auto`, throw up a timed prompt warning the user that these may fail to boot.

**Comment by zdykstra** [comment]
I'm checking for the wrong condition - whoops. I'll rework this to count and set a flag file that zfsbootmenu-init can check for.

**Pull request merged**
